export const allWEngineKeys = [
  'BashfulDemon',
  'BigCylinder',
  'BunnyBand',
  'CannonRotor',
  'DeepSeaVisitor',
  'DemaraBatteryMarkII',
  'DrillRigRedAxis',
  'ElectroLipGloss',
  'FusionCompiler',
  'GildedBlossom',
  'HellfireGears',
  'Housekeeper',
  'IceJadeTeapot',
  'KaboomTheCannon',
  'LunarDecrescent',
  'LunarNoviluna',
  'LunarPleniluna',
  'MagneticStormAlpha',
  'MagneticStormBravo',
  'MagneticStormCharlie',
  'OriginalTransmorpher',
  'PeacekeeperSpecialized',
  'PreciousFossilizedCore',
  'RainforestGourmet',
  'ReverbMarkI',
  'ReverbMarkII',
  'ReverbMarkIII',
  'RiotSuppressorMarkVI',
  'RoaringRide',
  'SharpenedStinger',
  'SixShooter',
  'SliceOfTime',
  'SpringEmbrace',
  'StarlightEngine',
  'StarlightEngineReplica',
  'SteamOven',
  'SteelCushion',
  'StreetSuperstar',
  'TheBrimstone',
  'TheRestrained',
  'TheVault',
  'TusksOfFury',
  'UnfetteredGameBall',
  'VortexArrow',
  'VortexHatchet',
  'VortexRevolver',
  'WeepingCradle',
  'WeepingGemini',
] as const

export type WEngineKey = (typeof allWEngineKeys)[number]

export const allUpgradeKeys = [1, 2, 3, 4, 5] as const
export type UpgradeKey = (typeof allUpgradeKeys)[number]

export const wEngineMaxLevel = 60
